apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      containers:
      - name: redis
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sleep"
                - "25"