apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

namespace: kubechecks

resources:
  - envoy_deploy.yaml

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml
      - tls.key
      - tls.crt